name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Mostrar entorno con secret NODE_ENV
        run: |
          echo "Entorno actual: ${{ secrets.NODE_ENV }}"

      - name: Mostrar API_KEY
        run: |
          echo "Tu API key es: ${{ secrets.API_KEY }}"
